# Generated by Django 2.2.1 on 2022-11-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mainscreen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(blank=True, max_length=500, null=True)),
                ('video_link', models.URLField(default='#', max_length=300)),
            ],
        ),
    ]
