# Generated by Django 2.2.1 on 2022-11-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainscreen',
            name='anxiety_test_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mainscreen',
            name='depression_test_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
