# Generated by Django 2.2.1 on 2022-11-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20221126_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='depression_articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(blank=True, max_length=500, null=True)),
                ('main_description', models.CharField(blank=True, max_length=500, null=True)),
                ('article_image', models.ImageField(upload_to='static/images')),
                ('article_heading', models.CharField(blank=True, max_length=500, null=True)),
                ('article_description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
