# Generated by Django 2.2.1 on 2022-11-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_depression_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depression_articles',
            name='main_description',
        ),
        migrations.RemoveField(
            model_name='depression_articles',
            name='main_title',
        ),
        migrations.AddField(
            model_name='mainscreen',
            name='depression_main_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mainscreen',
            name='depression_main_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
