# Generated by Django 2.2.1 on 2022-11-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20221126_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='depression_articles',
            name='article_link',
            field=models.URLField(default='#', max_length=300),
        ),
    ]
