# Generated by Django 2.2.1 on 2022-11-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_depression_articles_article_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='formdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(blank=True, max_length=500, null=True)),
                ('gender', models.CharField(blank=True, max_length=500, null=True)),
                ('survey_teken_before', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
