# Generated by Django 2.2.1 on 2022-11-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_formdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
